### ISSUE TITLE
Rule with misplaced whitespace compiled before and fails now

### ISSUE THREAD

**Issue by noullet** [SomMeri/less4j#306] opened 2015-10-08 09:53 UTC
Hi,

I rely on an external LESS theme which contains a rule like that:
```less
@line-height-computed: 20px;
pre {
      margin: 0 0( @line-height-computed / 2);
}
```

I assume that the whitespace should be located before the parenthesis, however it compiled fine with _less4j-1.10.0_ but does not compile with _less4j-1.11.0_ and above (because of the grammar refactoring?). Here is the error log:
```
java -jar less4j-1.11.0.jar test.less
Errors produced by compilation of test.less
ERROR 3:7 no viable alternative at input 'margin' in ruleset (which started at 2:1)
 2: pre {
 3:       margin: 0 0( @line-height-computed / 2);
 4: }

ERROR 3:7 no viable alternative at input 'margin' in ruleset (which started at 3:7)
 2: pre {
 3:       margin: 0 0( @line-height-computed / 2);
 4: }

ERROR 3:13 no viable alternative at input ':' in ruleset (which started at 3:13)
 2: pre {
 3:       margin: 0 0( @line-height-computed / 2);
 4: }

ERROR 3:15 no viable alternative at input '0' in ruleset (which started at 3:15)
 2: pre {
 3:       margin: 0 0( @line-height-computed / 2);
 4: }

ERROR 3:17 no viable alternative at input '0' in ruleset (which started at 3:17)
 2: pre {
 3:       margin: 0 0( @line-height-computed / 2);
 4: }

ERROR 3:18 no viable alternative at input '(' in ruleset (which started at 3:18)
 2: pre {
 3:       margin: 0 0( @line-height-computed / 2);
 4: }

ERROR 3:42 no viable alternative at input '/' in unknown ruleset (which started at 3:20)
 2: pre {
 3:       margin: 0 0( @line-height-computed / 2);
 4: }

ERROR 3:42 no viable alternative at input '/' in ruleset (which started at 3:42)
 2: pre {
 3:       margin: 0 0( @line-height-computed / 2);
 4: }

ERROR 3:45 no viable alternative at input ')' in ruleset (which started at 3:44)
 2: pre {
 3:       margin: 0 0( @line-height-computed / 2);
 4: }

ERROR 4:1 missing EOF at '}' in stylesheet (which started at 1:1)
 3:       margin: 0 0( @line-height-computed / 2);
 4: }

Could not compile the file test.less
```

It compiles fine with _less.js 2.5.3_ and this difference is not documented here (unless I missed something): https://github.com/SomMeri/less4j/wiki/Differences-Between-Less.js-and-Less4j

The rule can be easily fixed but I assume that the change in less4j behavior is not intentional because it is not documented and diverges from _less.js_, hence the issue.

**Comment by SomMeri** [comment] 2015-10-08 12:35
Thank you for reporting the error. This will be fixed in the next release, the bug got fixed along with #295. It had the same root cause as "math operation" problem mentioned there.

**Closed by SomMeri** 2015-10-08 12:35 UTC
Labels: bug

**Comment by noullet** [comment] 2015-10-08 12:49
Thanks for your quick feedback and thanks for the fix.

Have a good day!

**Comment by davydotcom** [comment] 2015-10-14 17:03
Just checking in on this blocked on a project. any ETA to next release? Want to push this out to `less-asset-pipeline` as soon as I can. Thanks

**Comment by noullet** [comment] 2015-10-15 08:03
@davydotcom Funny to see you here, actually I got this error from `less-asset-pipeline` through `less-grails-asset-pipeline` (I am currently stuck with `2.1.0` because of that). Glad to know that you are eager to push the fix!

**Comment by davydotcom** [comment] 2015-10-15 11:25
You can get around it by excluding less4j from the less asset pipeline
dependency and addinf less4j 1.10.0 to your dependencied block

**Comment by SomMeri** [comment] 2015-10-16 11:28
@davydotcom I will try to push it out, asap, within next few days. I originally through it would be released previous weekend.

I moved to new laptop and have to deal with unexpected problems (antlr3 does not work with java 8, maven-releas-plugin does not cooperate with newly installed maven, my old pgp key is not available for me now, and so on).

**Comment by davydotcom** [comment] 2015-10-16 11:41
Np completely understand the troubles with maintaining libraries. This is a
great plugin and sincerely appreciate the work put into it. Thanks for the
update ill pass that along.

**Comment by SomMeri** [comment] 2015-10-17 18:32
@davydotcom Less4j 1.15.0 was just released. If you have a problem with that, let me know. Hopefully everything is setup now (and I should be able to solve problems where it is not) so next releases can be done with very little work.
